cc: check for domain argument

diff --git a/lib/cc/lartcc++.in b/lib/cc/lartcc++.in
--- a/lib/cc/lartcc++.in
+++ b/lib/cc/lartcc++.in
@@ -12,6 +12,11 @@ LIBCXX="@LIBCXX_INSTALL_DIR@"
 LIBCXX_CFLAGS="-stdlib=libc++ -nostdinc++ -I${LIBCXX}/include/c++/v1"
 LIBCXX_LDFLAGS="-L${LIBCXX}/lib -Wl,-rpath,${LIBCXX}/lib"
 
+if [ -z $domain ]; then
+     echo -e "${RED}[LART ERROR]${NC} No domain provided. Please specify a domain name."
+     exit 1
+fi
+
 exec @CLANGPP_BINARY@                           \
      -Xclang -load -Xclang "$PASS"              \
      -fsanitize=dataflow                        \
diff --git a/lib/cc/lartcc.in b/lib/cc/lartcc.in
--- a/lib/cc/lartcc.in
+++ b/lib/cc/lartcc.in
@@ -7,6 +7,14 @@ RUNTIME="@PROJECT_BINARY_DIR@/lib/runtime/native/libnative.a"
 DOMAIN="@PROJECT_BINARY_DIR@/lib/lamp/lib$domain.a"
 PASS="@CMAKE_CURRENT_BINARY_DIR@/liblart_module.so"
 
+RED='\033[0;31m'
+NC='\033[0m' # No Color
+
+if [ -z $domain ]; then
+     echo -e "${RED}[LART ERROR]${NC} No domain provided. Please specify a domain name."
+     exit 1
+fi
+
 exec @CLANG_BINARY@                             \
      -Xclang -load -Xclang "$PASS"              \
      -fsanitize=dataflow                        \
